### ISSUE TITLE
Create and publish - IBM.com Style Model Grid Guideline

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#105]
> As an IBM.com Library adopter

> I need a guideline to follow and effectively use the IBM.com style model grid,

> so that I can create a consistent experience across the IBM.com.

---

#### ✏️ Additional information

- Website content publishing process detail can be viewed [here](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj).

#### Tasks
- [ ] Research and collect references
- [ ] Craft content and finalize the guideline content
- [ ] Design and finalize the guideline page design
- [ ] Create and publish the guideline on the website

#### Acceptance criteria
- [ ] IBM.com Style Model Grid Guideline published on the website.

**Comment by JennySanchez** [comment]
@wonilsuhibm This one is not on the Guideline [inventory list](https://airtable.com/invite/l?inviteId=inv3W25InvHBmTsLJ&inviteToken=3674d7d57ec5d8470f729a342c1f2c1da6a86e47ef0aa9611dbcae8fbaf22cf1) for publishing. Is the content part of the existing listed guideline or if we need to add this to the publishing list?

**Comment by RobertaJHahn** [comment]
@shixiedesign Should I move this issue to Sprint 21-08?

**Comment by shixiedesign** [comment]
Some basic research suggests-- 

### Component's background should extend beyond max width. 

Currently, only "Global" components get the full screen width background (eg. masthead and footer), and local(er) components do not have background extending beyond grid max width (1584px). This created some awkward white space on both sides of the screen.

On MBP (Display 2048 wide):  

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/df84df96-8d29-4392-b659-508649be6a40)
