### ISSUE TITLE
Ideation for the Birthday Cake version Components and Layout patterns overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#112]
#### Objective
Our current Components and Layout patterns overview page have two tabs so the adopters can view the inventory in both ListView and Tile View. However, based on the [designer feedback](https://ibm.box.com/s/ba4p4j0eclo7i5avz5kp8ubemijtas39) we need to explore ideas of how to combine the two viewing elements into one page and also allow the tagging and filtering or search features we are going to add for the wedding cake version. 

#### Tasks

- [ ] Get feedback from the development adopters to find out what needs they have when viewing  Components and Layout patterns inventory, so we know what else we need to consider.
- [ ] Work on design proposals to meet adopter needs.
- [ ] Review design proposals with Linda, Jeff, and Wonil for execution direction.
- [ ] Make a plan for prioritization and execution.

**Comment by JennySanchez** [comment]
This will be the 2021 focus.

**Comment by JennySanchez** [comment]
This task was opened in July 2020. We no longer have Layout patterns sections anymore, and this task will be closed.

**FYI:** @RobertaJHahn
