### ISSUE TITLE
?component name?:  Ideation epic template

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#120]
This epic contains an overview of the research and design performed to create this component. 

#### User Story 1 - End user
> As an [user role below]:
`ibm.com user`

> I would like to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### Additional Information
- [box folder]
- [reference materials]

#### Acceptance Criteria
- [ ] Research findings are available and posted to the Box folder
- [ ] Design exploration is done and results posted to the Box folder
- [ ] Agile board epic is created to begin the functional specs work
- [ ] Final design is done and posted to the Box folder

**Comment by ghost** [comment]
This epic contains an overview of the research and design performed to create this component. 

### User story 1: end user
> As an `[user role below]`:
ibm.com user

> I would like to be able to do:
?description here?

> so that I can:
?description here?

### Additional Information
- [box folder]
- [reference materials]

### Acceptance criteria
- [ ] Design specs are available
- [ ] Functional specs are available
- [ ] Codes are available
- [ ] Design guidelines are available
- [ ] Development documentations are available

**Comment by RobertaJHahn** [comment]
Closing as the Ideation repo concept no longer exists.
