### ISSUE TITLE
Lead space: variation research

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#127]
### User Story
> As an [user role below]:
`ibm.com user`

> I would like to be able to:
`orient myself and understand the content of the page`

> so that I can:
`make a decision on whether this page is relevant to me or not.`

### user story 2
> As an [user role below]:
`DDS designer`

> I would like to be able to:
`understand what kind of lead spaces are out there both internally and externally`

> so that I can:
`create a system of lead spaces.`

### Notes
We have the original size standards, which our current lead space component is based on. We have a few more lead space designs from the Reboot team (see the additional information section below). We want to create a system of variations that reflect the position in the user's journey and are still consistent and coherent.

### Additional Information
- **See the epic for the overarching descriptions of the work.**
- [box folder](https://ibm.box.com/s/d9jey3rlfxqmxu059f0x9dtcx7f5ehuh)
- [Original size standards](https://ibm.box.com/s/iy3rscrww6sz2ioz7qbxhee040m5727e)
- [Solutions page template](https://ibm.box.com/s/mtwz67xkesfe6wf038tw8z7h6atrus2f)
- [Services page template](https://ibm.box.com/s/4p0p344zjmu1e273u60g5ytjdasd1rs9)
- [Support landing page](https://share.goabstract.com/5ca0af92-0b72-4bf0-8486-91a109e23d33)
- [Products landing page](https://share.goabstract.com/ffb87f12-92f3-432f-87ba-107de1aeb796)

### Acceptance criteria
- [x] Lead space variations within IBM are collected
- [x] Lead space variations outside IBM are collected from the following competitors:
   - Google Cloud
   - AWS
   - Azure
   - Adobe
   - Anything else?
- [ ] Recommendation on how to use lead spaces in users' journeys
- [ ] The next story has been updated with the research findings

**Comment by larahanlon2** [comment]
### Lead space research report (WIP) can be found [here](https://ibm.ent.box.com/notes/717141700263).

### Competitor audit can be found [here](https://ibm.box.com/s/jyhzoysxeca8lenhz37gf8hfreoturjm).

**Comment by larahanlon2** [comment]
Final update on this work:

- [x] Lara presented research report, competitor audit and proposals to DDS and Reboot on October 1.
- [ ] The work needs to be discussed further with `content strategy` on Reboot side before final direction is agreed upon.
- [ ] Additional `design studies` or mapping of current lead space designs to page intents would be beneficial.
- [x] DDS designers need to continue `documentation` of guidelines.
- [ ] DDS and Reboot should review the `use of video` guidelines contributed by [Brian Tafel](https://w3.ibm.com/bluepages/profile.html?uid=3J3070897) before publishing this content. See the `use of video` section in the [WIP guidelines](https://ibm.box.com/s/00ayfghsn26ge4g19lcn59buylav2xix
- [ ] ) (this is all from Brian/Watson Health).

**Sketch file with competitor audits and internal audit/journey proposals:**
https://ibm.box.com/s/jyhzoysxeca8lenhz37gf8hfreoturjm

**Research report:**
https://ibm.box.com/s/2fywsn7qwhev2ay4ia3jknhh17ugx5vj

**Draft content for lead spaces pattern (to publish on IBM.com Library)**
Boxnote:
https://ibm.box.com/s/00ayfghsn26ge4g19lcn59buylav2xix
Sketch mockup:
https://ibm.box.com/s/00ayfghsn26ge4g19lcn59buylav2xix

**Comment by JennySanchez** [comment]
**Task update:** Follow-up call on this task scheduled for 10/26 Monday with @wonilsuhibm and Olivia as optional.

**Comment by ghost** [comment]
The outcomes as of November 23rd
- Lead space pattern MVP is being published
- Next steps will be working with adopters and partners to add details on top of these foundations.
