### ISSUE TITLE
Wedding Cake version content structure ideation.

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#130]
> As an IBM.com Library adopter,

> I need a way to view all the information about a component or a pattern

> So that I can see have a full understanding and learn all the detail I need to adopt a component or a pattern offered by the IBM.com Library.

#### Tasks

- [ ] Get feedback from adopter with the MVP version content
- [ ] Have a full list of the items we need to add to the MVP version content
- [ ] Work on the design in Sketch App to flush out the visual elements
- [ ] Update or create new templates for publishing
- [ ] Create the wedding cake version content publishing list and approved by the DDS leadership
- [ ] Prioritize the items on the list
- [ ] Create an individual publishing task on the Agile board for execution.

#### Acceptance criteria
A wedding cake version of the content structure is ready for execution.

**Comment by RobertaJHahn** [comment]
No longer needed.  Closing
