### ISSUE TITLE
Guided delivery on Dotcom Library

### ISSUE THREAD

**Issue by oscardumlao-ibm** [carbon-design-system/digital-design-ideation#134]
**Objective**
This epic aims to implement the big Tier 2 takeaways that came from the outcomes of the Patterns incubator program with Project Phoenix. We will create a new website flow and IA concept that focuses on intentionally showing a more limited range of assets relevant to specific visitor needs, what we call the _Create flow_ using the terminology from Patterns.

**Tasks**
- [ ] Iterate on different page flows for asset delivery
- [ ] Decide which asset delivery method makes most sense for creators
- [ ] Create left nav IA reflecting new asset delivery structure
- [ ] Determine the best design strategies in the content area of each page in the Create flow

**Acceptance criteria**
- [ ] Interactive Dotcom Library prototype demonstrating how creators can arrive at the single best resource for their objective

**Comment by oscardumlao-ibm** [comment]
Original Mural board defining objectives around this area: https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1598458857014?sender=oscardumlao4826&key=019be255-9cd5-4ad0-af28-1eebc69249ff
