### ISSUE TITLE
Prototype for template-first delivery

### ISSUE THREAD

**Issue by oscardumlao-ibm** [carbon-design-system/digital-design-ideation#135]
**Objective**
We are defining a new section for guided delivery on Dotcom Library. We'll create a prototype for this flow that explores what the UX would be for creators if we aimed to deliver page templates as the main solution for their needs.

**Tasks**
- [x]  Sketch mockup of entryway page 
- [x]  Sketch mockup of template selection page
- [x]  Sketch mockup of template details page(s)
- [x]  Sketch mockup of underlying style model page
- [x]  InVision flow connecting completed Sketch pages

**Acceptance criteria**
- [x]  Clickable prototype demonstrating whether or not creators can find what they need using a template-first approach

**Comment by oscardumlao-ibm** [comment]
Note: this is the closest to the originals Patterns work. Basis work found here: https://ibm.ent.box.com/file/710560342848 under the Create label in the Sketch canvas.

**Comment by oscardumlao-ibm** [comment]
InVision prototype: https://ibm.invisionapp.com/share/PHO0EWP6JBS#/screens/319684412
