### ISSUE TITLE
Prototype for style model-first delivery with Universal Experiences

### ISSUE THREAD

**Issue by oscardumlao-ibm** [carbon-design-system/digital-design-ideation#136]
**Objective**
We are defining a new section for guided delivery on Dotcom Library. We'll create a prototype for this flow that explores what the UX would be for creators if we aimed to deliver style models as the main solution for their needs.

**Tasks**
- [x]  Create systematic mapping for how Style Models fits Universal Experiences steps and touchpoints
- [x]  Sketch mockup of entryway page 
- [x]  Sketch mockup of style model selection page
- [x]  Sketch mockup of style model details page(s)
- [x]  InVision flow connecting completed Sketch pages

**Acceptance criteria**
- [x]  Clickable prototype demonstrating whether or not creators can find what they need using a style model-first approach that still works with Universal Experiences

**Comment by oscardumlao-ibm** [comment]
InVision prototype: https://ibm.invisionapp.com/share/4XO0F7TNE5B
