### ISSUE TITLE
Prototype for style model-first delivery with new gateway

### ISSUE THREAD

**Issue by oscardumlao-ibm** [carbon-design-system/digital-design-ideation#137]
**Objective**
We are defining a new section for guided delivery on Dotcom Library. We'll create a prototype for this flow that explores what the UX would be for creators if we aimed to deliver style models as the main solution for their needs.

**Tasks**
- [x]  Competitive audit of website design guidance
- [ ]  Sketch mockup of entryway page 
- [ ]  Sketch mockup of style model details page(s)
- [ ]  InVision flow connecting completed Sketch pages

**Acceptance criteria**
- [ ]  Clickable prototype demonstrating whether or not creators can find what they need using a style model-first approach without the framing of Universal Experiences

**Comment by oscardumlao-ibm** [comment]
Added new task of competitive audit looking at Squarespace etc. for how to deliver pre-built frameworks to web creators.

**Comment by oscardumlao-ibm** [comment]
Flow map for question logic: https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1599167621015?sender=oscardumlao4826&key=88009037-afdd-4acc-88ea-b0ed819bbe7f

**Comment by oscardumlao-ibm** [comment]
Closing out this task because we are pivoting away from this concept completely (neither style models nor templates comes first)
