### ISSUE TITLE
Scroll animation: design epic

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#144]
This epic contains an overview of the research and design performed to create this component. 

#### User Story 1 - End user
> As an [user role below]:
`ibm.com user`

> I would like to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### Additional Information
- [box folder]
- [reference materials]

#### Acceptance Criteria
- [x] Research findings are available and posted to the Box folder
- [ ] Design exploration is done and results posted to the Box folder
- [ ] Agile board epic is created to begin the functional specs work
- [ ] Final design is done and posted to the Box folder

**Comment by photodow** [comment]
Here is my first pass at the scrolling design research. I'll add it to our critique on Friday to review if you'd like.

https://ibm.box.com/s/9izcfoxb04wkxoa5ycewn9bfrdtup7fb

**Comment by RobertaJHahn** [comment]
Moving this work to be managed under Carbon for ibm.com epics so that the Roadmap feature works.  The linked issues have been moved to [epic 753](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/753) and [epic 4766](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/4766)
