### ISSUE TITLE
Research and Planning for website content crafting best practice

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#147]
> As an IBM.com Library team members,

> I need to follow a guideline when creating the website content

> so that I can create and provide the right assets.

#### Task
- [ ] Do research around what we need to address when creating content for the website.
- [ ] Decided how or where we are going to publish the best practices for internal use.

#### Acceptance criteria
- [ ] Have a list of what we are going to include in the best practice.
- [ ] Create a task issue/issues for best practices creation on the Agile board.

**Comment by JennySanchez** [comment]
We added basic guidelines to the Carbon for IBM.com [Production guidelines - Writing content section](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Carbon-for-IBM.com-Production-guidelines) for now and will add more items as we go in 2021.

**Comment by RobertaJHahn** [comment]
Closing.  Will create new issues as we see a need in the future.  Ref issue (#722)
