### ISSUE TITLE
Discussion + Ideation: website linking strategy (short term solution)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#148]
### Focus: How can we have IBM.com Library information from the Carbon website

---

@JennySanchez commented on [Thu Mar 19 2020](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/367)

> As a NEW IBM.com Library adopter,

> I need a way to get to the IBM.com Library website from the Carbon website, 

> So that I can tell the differences or relationships between the Carbon and IBM.com Libray without confusion.

#### Task
- [x] Review the adopter pain point around getting confused between the two design system websites.
- [ ] Ideate and come up with proposals on how we can surface the IBM.com Library link on the Carbon homepage and other critical pages such as Resource Page.

#### Acceptance criteria
- [x] Have a proposal for us to open a Git issue on Carbon's repo.

---

@stale[bot] commented on [Fri May 22 2020](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/367#issuecomment-632942616)

We've marked this issue as stale because there hasn't been any activity for 60 days. If there's no further activity on this issue in the next three days then we'll close it. You can keep the conversation going with just a short comment. Thanks for your contributions.

---

@stale[bot] commented on [Mon May 25 2020](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/367#issuecomment-633741683)

As there's been no activity since this issue was marked as stale, we are auto-closing it.

---

@JennySanchez commented on [Mon Sep 14 2020](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/367#issuecomment-692207969)

@wonilsuhibm It's my understanding you had a few conversations with Mike and the Carbon Team around the linking strategy (Short Term) between the IBM.com Library and Carbon websites. Can you share the latest discussion highlight here?

---

@JennySanchez commented on [Tue Sep 22 2020](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/367#issuecomment-696958528)

Mike set up a regular bi-weekly meeting for the website linking discussion. 

The focus area will be as the following:
1. — About pages (explain Carbon system landscape clearly in both Carb/IBM.com and IDL)
2. — Left nav / IA between two sites. What stays unique, what can merge, and what is mirrored. etc.
3. — Home pages for each
4. — Naming for a top nav solution (e.g. Product design | Website design )

Based on the discussion Wonil, Linda, and I had earlier today, we are aligned on the directions and will start by looking at the navigation differences to facilitate the discussion next week. For now, this task issue will be moved to the ideation board and the continuous discussion detail will be recorded here. When we have a list of action items for the interim solution, individual task issues will be created on the Agile board for execution.

**Comment by JennySanchez** [comment]
@ljcarot @wonilsuhibm 

Mural board set up for ideation based on our conversation yesterday can be viewed [here](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1600808396496?sender=chsanche&key=57a2b85e-f368-461f-8899-4cd296b996ef).

**Comment by JennySanchez** [comment]
For the short term solution, internally, we will update the left navigation labels to match the direction on the Carbon website.

On the carbon side, the Carbon website will add a tab to take the adopters from the Carbon website to Carbon for the IBM.com website. @wonilsuhibm Is there anything missing from the short term solution mentioned here from your discussion with Mike and LInda?
