### ISSUE TITLE
Ideation: IBM Standard website checklist treatment

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#150]
#### Objective

IBM.com content creators need a way to find the standards and a checklist to help them complete IBM compliance standards before presenting the content to the end-user who visited IBM.com.

#### Task

- [x] Talk to Linda and find out what is included on the checklist.
- [x] Do design research and study how other websites present similar content. 
- [x] Explore ideas and locations on where the list should live on the standard website.

**Comment by JennySanchez** [comment]
FYI: @wonilsuhibm @ljcarot

**Comment by JennySanchez** [comment]
#### Note
One of the idea to explore - On page tab treatment
![Screen Shot 2020-09-23 at 12.15.09 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/e64dfa72-e8cf-46a6-80a7-e462accb56f1)https://www.ibm.com/design/thinking/page/badges/core-skills

**Comment by JennySanchez** [comment]
**Task update:** Jo, Linda and I met yesterday (11-02-2020) and Jo went over the expectation and her findings with us.

**Comment by JennySanchez** [comment]
**Meeting Note:**
- We will take the "How do I...?" approach.
- Consider taking care of the page without the left nav on the IBM Design page.
- Jo mentioned the content should be ready in two weeks and we will have two weeks to work on the design.

**Comment by JennySanchez** [comment]
@ljcarot 

- The Mural board we looked at during the meeting can be found [here](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1605552922221?sender=chsanche&key=58d9b899-325e-4719-94b8-b188e0490571). I added a link to the screenshots so you can take a look at the actual site by double-clicking on the image if you would like to explore more.

- I reached out to [Scott Strubberg](https://w3.ibm.com/bluepages/profile.html?uid=3G1780897) about the IBM [Design Tool website](https://w3.ibm.com/design/toolbox/#/accessibility-tools/README) as discussed.  He told me the website was built with "[Docsify](https://docsify.js.org/#/)", a documentation site generator. He mentioned he is going to build a new website and move the content to the Carbon for Gatsby themed website. It's because the Carbon Gatsby theme is a much more powerful tool for website content, more IBM branded, and most importantly it's supported.

**Comment by JennySanchez** [comment]
Task issue #748 Design the Checklist for IBM.com Web Standard website created for the next step.
https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom-website/748
