### ISSUE TITLE
Audio Player:  design epic

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#162]
This epic contains an overview of the research and design performed to create this component. 

#### User Story 1 - End user
> As an [user role below]:
`ibm.com user`

> I would like to be able to:
`listen to audio files`

> so that I can:
`access the information I need on the ibm.com website`

#### Additional Information
- This feature request was opened by the MediaCenter adopter under Agile board [epic 4083](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/4083) **See this epic for details of their request and comments from the initial meeting with them.**
- [Audio examples provided by the MediaCenter adopter](https://pages.github.ibm.com/mediacenter/docs/examples/audio/)
- This audio file will be hosted in the Kaltura application and will be implemented using the Kaltura API.
- [Northstar audio player](https://www.ibm.com/standards/web/v18/design/audio-player/)

#### Acceptance Criteria
- [ ] Design exploration is done and results posted to the Box folder
- [ ] Agile board epic is created to begin the functional specs work
- [ ] Final design is done and posted to the Box folder

**Comment by RobertaJHahn** [comment]
Closing.  This work will be managed under epic (#4083)
