### ISSUE TITLE
 Ideation: IBM.com Web Standard website hero image

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#165]
#### Objective
We need to add a hero image to the IBM.com web standard website to create a better impression when IBM.com content creators landed on the homepage.

#### Task

- [ ] Do design research and study how other IBM websites present similar content (style of the hero images or hero section treatments).
- [ ] Explore ideas and create purposed designs.
- [ ] Review the designs with Linda and Wonil.
- [ ] Finalize the design and create task issues on the Agile board for execution.

**Comment by JennySanchez** [comment]
**Note:**

![Screen Shot 2020-09-29 at 8 00 34 AM](https://user-images.githubusercontent.com/45213839/96015787-95788780-0e0d-11eb-81f1-b0fbfb7d0ed3.png)

**Comment by RobertaJHahn** [comment]
If this is not worked on by the end of June 2021 then can close.

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/carbon-for-ibm-dotcom #5934](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5934) via [**ZenHub**](https://www.zenhub.com/)
