### ISSUE TITLE
Card icon position standards

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/digital-design-ideation#174]
Icon on the left? Icon on the left is the main question.

See the visuals in the comment below.

This story is to finalize the standards and rules.

### Resources and artifacts
- [Box folder](https://ibm.box.com/s/aceic968uuwch0phkg6h35k05jiky6dd)
- [Mural board for card pattern audit](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1603999251939?sender=wonilsuh19286&key=b629fd92-bfad-4957-9592-3fbd72fb94b7)

### Tasks
- [ ] Talk to Product Discovery and Reboot teams to test
- [ ] Share with Carbon
- [ ] Finalize the standards

**Comment by ghost** [comment]
The latest rule/guidelines that we discussed is this:

<img width="1042" alt="Screen Shot 2020-10-29 at 11 03 29 AM" src="https://user-images.githubusercontent.com/30183447/97593830-71ee3900-19d8-11eb-8380-bed148f65df5.png">

The Sketch file for the above image is [here](https://ibm.box.com/s/9n8ejb8ful415pr0sepsqts5lf5iuh2e).

**Comment by ghost** [comment]
The latest icon positioning logic:
![patterns--cards--icon-position](https://user-images.githubusercontent.com/30183447/99084210-aa734280-2594-11eb-8544-14ff5f140f7c.png)

**Comment by ghost** [comment]
PR has been approved and merged.

**Comment by JennySanchez** [comment]
**Note:** 
Case one + two - [code is available](http://ibmdotcom-react.mybluemix.net/?path=/story/components-card--default).
Case three - code is not available.

**Comment by photodow** [comment]
@JennySanchez case two should be available. See below...

<img src="https://user-images.githubusercontent.com/3793636/99443390-5e036c00-28e0-11eb-975a-463a87721e83.png" width="250px" />

**Comment by JennySanchez** [comment]
Thank you @photodow. Note updated and Storybook link added.
