### ISSUE TITLE
Create MVP version content structure, template, and priorities

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#20]
### Goal
This story is to figure out what is the content MVP that will be helpful to our adopters.

#### Tasks

**Estimated task time: 4 weeks**
**Starting date: 05/11**

- [x] Compose lists of Pattern and Component page sections for adopter card sorting exercise based on what we currently have on the website and from the Carbon content templates (05/11 to 05/15).
- [x] Work on the Testing Plan and set up Mural.ly Board for the card sorting exercise (05/11 to 05/15).
- [x] Schedule and complete the card sorting exercise with adopters (05/18 to 05/22).
- [x] Synthesizing the findings (05/27 to 06/05).
- [x] Playback to the stream leads and Wonil to finalize the priority (05/27 to 06/05).

#### Acceptance criteria
- [x] Have a list of content sections to be swarmed around and start the content template updates.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc as mentioned in our task kickoff today, we need to add the section items from our current web page and the template to prepare the Card Sorting exercise we are going to do with the adopters on the [Mural.ly board](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1579113436354?sender=chsanche&key=26c3f47a-f226-44aa-bee7-223107a17b94).

I took the screenshots and added the links to the Patterns and Components templates on the board so you should have what you need to get started.

Please let me know if you have any questions.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Here's the [list](https://ibm.box.com/s/wv8p20m5t3l3n3xn0250ut2zcge9oa6l) of the Sponsor adopters we can reach out and schedule the Card Sorting exercise with for next week.

**Comment by jacobottesen-dgc** [comment]
Test script for card sort is ready and Mural board 

https://ibm.box.com/s/gqs2yd53wwbwga8qksuse5js7vy4b74g
https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1589488541451/1242c6b8ddb9d0cda9d9dc71dc9e65cf7521487e

**Comment by JennySanchez** [comment]
@jacobottesen-dgc I can not access the revised Test Scrip. Can you make sure it's saved in the Website folder? I created a folder for you and can be found [here](https://ibm.box.com/s/ykb0ljynf1horw2ipr8zk48qc9o8ka1h).

**Comment by jacobottesen-dgc** [comment]
Scheduled card sort activity with Pete, Shixie, & Lila for this week (05/18-22)

**Comment by JennySanchez** [comment]
**Update:** Playback session scheduled for 05/03.

**Comment by JennySanchez** [comment]
:point_right: The MVP content structure Mural for playback can be viewed [here](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1589488541451?sender=jacobottesen7512&key=a0e8258c-15d5-43ec-9bb8-755077f00750).

:point_right: The next step is for the stream leads to craft the To-Be content structure and used as a template for content publishing by the team.

**Comment by JennySanchez** [comment]
@wonilsuhibm I am glad we get to take a look at the content priority together yesterday. Please let me know if the list looks good to you and if there's anything we need to flag or move before sharing with the team.

**Comment by wonilsuhibm** [comment]
@JennySanchez Overall, this sounds good to me.
