### ISSUE TITLE
(MVP version) Update Components page content template

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#4]
### Objective
- Update the current [content template](https://ibm.box.com/s/oeifaq2ioa0huxuv59ixuhn1t9qf5x9r) for the [Components section](https://ibm-dotcom-library.mybluemix.net/components/footer) based on [the adopter needs](https://github.com/carbon-design-system/digital-design-ideation/issues/20).

### Tasks
- [ ] Set up a meeting to review adopter needs around Components.
- [ ] Discuss ideas.
- [ ] Create the template.
- [ ] Create next step stories if needed.

**Comment by JennySanchez** [comment]
Based on the discussion with Wonil. We are good to close this task and crafting content with the MVP version content template (#20) for Q3. We will work on the next iteration of the template via #104.
