### ISSUE TITLE
Adopter pain points study and alignment

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#43]
> As an IBM.com Library website content creator,

> I need a way to understand adopter pain points and know what are the big ideas for me to work on, 

> so that I can help adopters and eliminate the user pain points.

### Task

**Estimated task time: 4 weeks**
**Starting date: 05-03**

- [x] Collect all adopter pain points from stream leads (05/03 to 05/08).
- [x] Do pain points and needs grouping exercise to spot high-level pain points and needs (05/11 to 05/15).
- [x] Do pain points and needs category Prioritize exercise (05/18 to 05/22).
- [x] Synthesizing the findings (05/27 to 06/05).
- [x] Playback to the stream leads and Wonil to finalize the priority ~~(05/27 to 06/05)~~ (06/08 to 06/12) date changed due to the Hills workshop.

### Acceptance criteria
- [x] Have an aligned understanding and priority of what we are trying to solve and know where to get started.

**Comment by JennySanchez** [comment]
Note: Reach out to Lara about the #44 outcome.

**Comment by JennySanchez** [comment]
@wonilsuhibm  FYI: Mural board new section created for the adopter pain points and needs collection and can be viewed [here](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1579113436354?sender=chsanche&key=26c3f47a-f226-44aa-bee7-223107a17b94).

**Comment by JennySanchez** [comment]
Based on the conversation with Wonil and Linda, the Publishing Swarm will be the priority for Q2.  Publishing Swarm Epic can be viewed [here](https://github.com/carbon-design-system/digital-design-ideation/issues/3) on the Ideation Board.

**Comment by JennySanchez** [comment]
**Task update:** We went over the adopter pain point findings and categorize the pain points and needs. Our next step is to look into the pain points and needs one level deeper in detail and complete the prioritization Grid exercise on Wednesday 05/20.

**Comment by JennySanchez** [comment]
**Update:** Playback session scheduled for 05/03.

**Comment by JennySanchez** [comment]
**Findings:** Overall, the outcome from the stream leads, and designers are almost one to one with the To-Be sitemap. 

![Screen Shot 2020-06-01 at 3 51 10 PM](https://user-images.githubusercontent.com/45213839/83453314-e3bd5900-a41f-11ea-831c-84491977da83.png)

**Comment by JennySanchez** [comment]
Task completed and priority will be confirmed and shared via #20. We will continually use the Mural as a resource for further discussion.
