### ISSUE TITLE
IBM.com style model: design intent validation and baselining

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#47]
Work with Reboot team to collate, identify gaps, and update the list of design intents in order to make sure the style model framework is applicable to larger spectrum of touchpoints.

### Tasks
- [ ] Collate low level design intents from the current model
- [ ] Interview content strategists, taxonomists, and IA strategists to validate
- [ ] Collect competitors' designs and collate under the identified intents
