### ISSUE TITLE
Website traffic tracking tooling research and planning

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#48]
> As an IBM.com Library website content creator,

> I need a way to track the traffic on the website, 

> so that I know how many adopters visit the website and if the website visiting rate is growing through time.

### Task

**Estimated task time: 3 weeks
Starting date: XX/XX**

- [ ] Understand what tools or methods we currently use for traffic tracking.
- [ ] Learn more about what Leadership Team is looking for when it comes to a website (ex: NPS, feedback outcome, etc).
- [ ] Craft a purposed traffic tracking plan along with cadence set up
Review the plan with the Leadership Team.

### Acceptance criteria
- [ ] Have an aligned plan ready for execution.

**Comment by JennySanchez** [comment]
@wonilsuhibm FYI on this task existed. We will need to create an EPIC and set priority.

**Comment by JennySanchez** [comment]
**Note:**
In the past, we used Hotjar for NPS tracking then add the outcome into an [Excel document](https://ibm.box.com/v/DDS-Heatmap-Summary) and the process is fairly complex (see reference below).
![Screenshot_2020-05-19 DDS Hotjar Heatmaps xlsx Powered by Box](https://user-images.githubusercontent.com/45213839/82338319-5d7e2d00-99b2-11ea-8632-51bc19efe0ff.png)

**Comment by JennySanchez** [comment]
This Epic is no longer relevant to our work or priority and will be closed.
FYI: @RobertaJHahn
