### ISSUE TITLE
(MVP version) Update Layout Pattern content page template

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#5]
### Objective
- Update the current [content template](https://ibm.box.com/s/hmtss7ois6x5au7kgv9wox4fmy76e1a2) for the [Layout Patterns section](http://ibm-dotcom-library.mybluemix.net/patterns/leadspace) based on [the adopter needs](https://github.com/carbon-design-system/digital-design-ideation/issues/20).

### Tasks
- [ ] Set up a meeting to review adopter needs around Layout Patterns.
- [ ] Discuss ideas.
- [ ] Create the template.
- [ ] Create next step stories if needed.

**Comment by JennySanchez** [comment]
Based on the discussion with Wonil. We are good to close this task and crafting content with the MVP version content template (#20) for Q3. We will work on the next iteration of the template via #104.
