### ISSUE TITLE
Website traffic tracking tooling research

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#54]
### Objectives
This task is to look at the Website traffic tracking methodology and tools in the industry so we can find the best tool for us to see the growth measurement of the website.

**NOTE:** The tool needs to be IBM approved before implementation.

**Comment by JennySanchez** [comment]
Talk to Matt and learn...

- [ ] What are the traffic tracking goals for the Carbon website?
- [ ] Why did he decide to use Fathom?
- [ ] What are the Pros and Cons of using Fathom for traffic tracking?

---

The Carbon Team is using [Fathom](https://app.usefathom.com/share/vmsgxqrs/carbondesignsystem.com#/?from=2020-04-21%2000%3A00%3A00&site=2285&to=2020-04-28%2023%3A59%3A59) to collect data on the Carob Website. Matt is the owner of this task and tool. 

![Screen Shot 2020-04-28 at 4 00 49 PM](https://user-images.githubusercontent.com/45213839/80537316-73776f80-8969-11ea-97ac-7ad7442b90fc.png)

**Comment by JennySanchez** [comment]
Talk to Scott Strubberg and learn...

- [ ] What are the IBM approved tools for NPS tracking?
- [ ] Share our objectives and see if he has any recommendations?

---
Scott built [Design Toolbox](http://designtoolbox.w3ibm.mybluemix.net/#/) hub last year as an open-contribution site for the tracking of software titles and services that we need to get our job done. He also knows a lot of tooling usage from the product teams across IBM.

<img width="895" alt="Screen Shot 2020-05-07 at 9 45 54 PM" src="https://user-images.githubusercontent.com/45213839/82734915-a05a4080-9ce3-11ea-943d-21dfe61354c5.png">

**Comment by RobertaJHahn** [comment]
Google Analytics is being used.  Reports are being created weekly.  Closing
