### ISSUE TITLE
(MVP version) Create Guideline content page template

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#6]
### Objective
- Create a content template for the [Guideline section](https://ibm-dotcom-library.mybluemix.net/guidelines) based on [the adopter needs](https://github.com/carbon-design-system/digital-design-ideation/issues/20).

### Tasks
- [ ] Set up a meeting to review adopter needs around Guidelines.
- [ ] Discuss ideas.
- [ ] Create the template.
- [ ] Create next step stories if needed.

**Comment by JennySanchez** [comment]
Based on the discussion with Wonil. We are good to close this task and crafting content with the MVP version content template (#20) for Q3. We will work on the next iteration of the template via #104.
