### ISSUE TITLE
Planning for Pattern ontology content publishing on the website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#60]
@JennySanchez commented on [Mon Mar 23 2020](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/372)

(Task created as one of the action items from the Gatsby Theme website building process retro #242).

> As an IBM.com Library adopter,

> I need to understand how the pattern ontology works,

> so that I can create with confidence.

#### Task
- [ ] Discuss what we should provide to our adopters around the ontology work.
- [ ] Decided what we need to publish.

#### Acceptance criteria
- [ ] Have a clear idea of what we are going to include in the ontology education section or page.
- [ ] Create a task issue/issues for content creation.

---

@stale[bot] commented on [Fri May 22 2020](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/372#issuecomment-632942598)

We've marked this issue as stale because there hasn't been any activity for 60 days. If there's no further activity on this issue in the next three days then we'll close it. You can keep the conversation going with just a short comment. Thanks for your contributions.

---

@stale[bot] commented on [Mon May 25 2020](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/372#issuecomment-633741701)

As there's been no activity since this issue was marked as stale, we are auto-closing it.

**Comment by JennySanchez** [comment]
@wonilsuhibm I think this task is no longer relevant. Can you confirm?

**Comment by JennySanchez** [comment]
This task is no longer relevant and the task issue will be closed.
