### ISSUE TITLE
Planning for create website artwork and visual reference guideline

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#61]
@JennySanchez commented on [Mon Mar 23 2020](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/371)

(Task created as one of the action items from the Gatsby Theme website building process retro #242).

> As an IBM.com Library team members,

> I need to follow a guideline when creating a visual reference for the website content

> so that I can create and provide the right assets.

#### Task
- [x] Do research around what visual references we have on the website.
- [x] Decided what we need to include in the guideline.

#### Acceptance criteria
- [x] Have a list of what we are going to include in the guideline.
- [x] Create a task issue/issues for guideline creation.

Note: Get Kenny or Jeff involved in the task can ensure we cover the dev requirements as well.

---

@stale[bot] commented on [Sat May 23 2020](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/371#issuecomment-633140113)

We've marked this issue as stale because there hasn't been any activity for 60 days. If there's no further activity on this issue in the next three days then we'll close it. You can keep the conversation going with just a short comment. Thanks for your contributions.

---

@stale[bot] commented on [Tue May 26 2020](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/371#issuecomment-634330166)

As there's been no activity since this issue was marked as stale, we are auto-closing it.

**Comment by sethibm** [comment]
Created "Image Guidelines" folder for now in Cupcake Website folder, with a Sketch file showing some work there.
https://ibm.box.com/s/arg3tocb8vvpf2g4nq4g3ac3ndwoajrr

This is Invision of that Sketch:
https://ibm.invisionapp.com/share/3HO0AND9GJN#/319641775_Pattern_Pages_-_Sample_Image_Sizes

**Comment by JennySanchez** [comment]
#### Area of focuses:

- Image size - Guideline, Components, Layout patterns, and general.
- Image converting - Step-by-step with the artboard set up.
- Exporting - Format, naming, etc. Note: how to make the image looks crispy
- Spec image - What to include, label colors, etc.

**Comment by JennySanchez** [comment]
![Screen Shot 2020-09-18 at 10 41 18 AM](https://user-images.githubusercontent.com/45213839/93617371-8122a580-f99b-11ea-9447-b39001b6b0fc.png)

**Comment by JennySanchez** [comment]
We included the image set up step by step in the Sketch template and add guidelines for image creation in the Production Guideline. This task will be closed for now and we will continue adding more guidance as we go.
