### ISSUE TITLE
Planning for Early adopter starter kit development

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#62]
#### Objective

The website stream is developing the Early adopter starter kit. Even we have a list of the collective Sketch files and resources, we need to understand what we should include in the kit and how can the adopters access the folder so we can craft the best experience for the adopters.

#### Tasks
- [x] Understand the adopter's needs for getting started and how the current experience is (As-Is). **FYI:** [The Adopter pain points and needs study](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1579113436354?sender=chsanche&key=26c3f47a-f226-44aa-bee7-223107a17b94) on the Mural might be a good place to start.
- [x] Understand the possible roadblocks and explore ways to store for better share the adopter kit (ex: a box folder and adopter has to request access like our design kit) with adopters without concerns.
- [x] Ideate on the possible resources (file, document, etc) to meet adopter needs for the future experience (To-Be).
- [x] Review what we currently have in the [adopter starter kit folder](https://ibm.box.com/s/ji9d47sf6r2e4z3vdhjuq2uk4ko02i65) and create a list of the items we need to work on for the kit.

**Comment by jacobottesen-dgc** [comment]
- Interviewed a partner adopters - Tam & Annmarie on June 12th
- Scheduled sync up meeting with Wonil for June 15th

**Comment by jacobottesen-dgc** [comment]
- Interviewed Reda, Sina, Edwy (partner adopters) for the adopter starter kit on June 12th

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Can you share the adopter finding documents here? Thanks!

**Comment by jacobottesen-dgc** [comment]
cc. @JennySanchez 

Here is the Mural board with adopter insights: https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1592233324885/2acaf91ca313ab336bbdc274a34093b8419475e7

**Comment by jacobottesen-dgc** [comment]
Meeting schedule for June 17th to discuss insights from adopters and next steps.

**Comment by jacobottesen-dgc** [comment]
Box note with next steps for starter kit: https://ibm.box.com/s/9i5zwckrl1nv8pk2tf7dy7tkxd8r4h1u
