### ISSUE TITLE
Updating or creating resources for the Early adopter starter kit

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#63]
#### Objective

The website stream is developing the Early adopter starter kit. We need to make sure we have the up to date resource files in the kit.

#### Tasks
- [x] Create a list of what documents are included and what they for so the adopters know which file to use.
- [x] Updating and working on the resources files we need to include in the early adopter starter kit.
- [x] Review the kit with Wonil and stream leads.

**Comment by jacobottesen-dgc** [comment]
Started working on a list of IBM design sites in Box note: https://ibm.box.com/s/185hpqq84pt77dkx8v6mzq2dt271bzsd

**Comment by jacobottesen-dgc** [comment]
Mural board with next steps https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1592849977529?sender=jacobottesen7512&key=f0141688-cc36-4e65-9bf0-44802b9166b7

Currently working on: 

- Contact & Approvals box note
- Updated READme
- Getting started folder

**Comment by jacobottesen-dgc** [comment]
Contact list & org chart are finished: https://ibm.box.com/s/i263vhtnljgyrfachw072ap6f5lz9rxp

**Comment by jacobottesen-dgc** [comment]
Had a meetings with Linda and Wonil to discuss kit next steps on July 8th.

**Comment by jacobottesen-dgc** [comment]
Scheduled to review work with Wonil July 14th.

**Comment by jacobottesen-dgc** [comment]
Finish adopters starter kit. Folder and files can be viewed here: https://ibm.box.com/s/42z8wj0jin5ip2c6uffzuxz7618wncew
