### ISSUE TITLE
Inspiration library Development

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#66]
> As an IBM.com library adopter,

> I need a way to see the work from other IBM.com designers

> So that I can see actual examples for inspiration.

#### Tasks
- [ ] Design research on how other design systems and teams handle the inspiration library.
- [ ] Define what information needs to be included
- [ ] Craft the experience with a prototype for testing
- [ ] Work on the design
- [ ] Code the finalized design
- [ ] Publish the content and implement the library on the website.

#### Acceptance criteria
Inspiration library lives on the website and shared with the IBM.com teams.

#### Next step:
- [ ] Epic is reviewed and prioritized for creating sub-issues for execution.

**Comment by JennySanchez** [comment]
**Note:** A filter feature will be great for the library. The search filters can be around 

- Component
- Color theme
- Pattern
- IBM.com style model type

**Comment by RobertaJHahn** [comment]
@JennySanchez This epic is awfully old.  Can't we close it?

**Comment by JennySanchez** [comment]
@RobertaJHahn I am trying to reviewing all the website task issues this sprint, and I still need this Epic for another Sprint or two. I will make sure I close it if we no longer need it in a sprint or two.

**Comment by JennySanchez** [comment]
After reviewing the priorities with Linda, this Epic is identified as a Medium priority. We will create proper task issues to get the Epic moving. FYI @RobertaJHahn

**Comment by shixiedesign** [comment]
We will inspire people later. First we need to figure out how to put on pants.
