### ISSUE TITLE
Guidelines section publishing roadmap planning

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/digital-design-ideation#67]
_chsanche created the following on Mar 26:_  

 # As a Digital Design System adopter, I need guidelines for me to follow, so that I can complete my tasks without confusion or contribute confidently because of I know how to do it.

### Notes

- We need to create the Guideline section on the website
- There are multiple guidelines we currently do not have and need to be crafted so we can publish the guidelines on the website. 

**(initial list)**

- [ ] Accessibility - Overview, Color, Keyboard, Developer.
- [ ] Content - General, Guidance, Glossary.
- [ ] Color - Overview, Usage.
- [ ] Iconography - Library, Usage Contribute.
- [ ] Layout
- [ ] Motion - Basics, Choreography, Resources.
- [ ] Spacing 
- [ ] Themes 
- [ ] Typography - Overview, Productive, Expressive.
- [ ] Contribution - Governance, Designers, Developers, Add-ons

### Acceptance criteria

- [ ] Our adaptor can find the guidelines they need on the DDS website.
- [ ] Guidelines will be published on the website under the "Guideline" section (coming soon).

### Tasks

- [ ] Review the guideline submission
- [ ] Review the guideline design
- [ ] Review the design with the developer
- [ ] Developer prep to write code 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/663_

**Comment by JennySanchez** [comment]
Guideline section publishing inventory list can be viewed [here](https://airtable.com/invite/l?inviteId=invsPWNzmNrcdba7F&inviteToken=7e3bdc4d60963b8e9e366bf6fd6d2de10c5e771772135b019515a62de1f7f430).
Guideline section publishing prioritization detail can be viewed [here](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1598615364665?sender=wonilsuh19286&key=7e8d6467-71c5-47fe-83f6-06bb61383a2d).
Guideline section publishing work can be viewed via **Create and publish new content for the Guidelines section on the website** epic [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/646).
