### ISSUE TITLE
Update Website content publishing process document

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#7]
> As an IBM.com Library website content creator,

> I need a way to share the content publishing process with the team members, 

> so that the team members can be aligned on the expectations when it comes to website page content creation. 

### Task

**Estimated task time: 2 weeks**
**Starting date: XX/XX**

- [x] Take a look at the 2020 website content publishing process [BOX document](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj) and make sure the process still works with the latest content content structure' (outcome of #20 ).
- [x] Update the document as needed.
- [x] Share the finalized document with the team members.

### Acceptance criteria
- [x] Have an aligned publishing process document for team members to use as a reference.

**Comment by JennySanchez** [comment]
Since we are publishing the content in the MVP version for Q3. We will pivot and take a look at the process in Q4 for refinement by collecting feedbacks from team members based on the Q3 publishing experience.

**Comment by JennySanchez** [comment]
**Task update:**

- Worked on the [process BOX document](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj) update with @wonilsuhibm today.
- Signed up for sharing the process document in the [DDS Team huddle](https://ibm.box.com/s/g3bpwxwyknpqldhg8uxfv2n5hka1rvi5) on 07/23.

**Comment by JennySanchez** [comment]
Followed up with Wonil via Slack to see if there's anything else we need to add to the document before the share today.

**Comment by JennySanchez** [comment]
**Document shared in the DDS Team Huddle today and on the Team Slack channel.**

![Screen Shot 2020-07-23 at 5 01 02 PM](https://user-images.githubusercontent.com/45213839/88343088-36234380-cd06-11ea-804a-23411722fc6c.png)



Task | Stage | Tool | Action | Dependencies | Contributor/Task owner | Sprint & LOE
-- | -- | -- | -- | -- | -- | --
Initial research | Research/Investigate | (Ideation board) | Identify adopter pain pointsIdeateIdentify proper IA placementIdentify proper level of details and fidelity | Adopter needs and pain points | Assignee/Content creator | Ideation
Publishing agreement | Planning | (Ideation board) | Get the content needs agreed by the DDS leadersGreat proper Epic or Task issue on Git for prioritization |   | Proposed by JennyApproved by DDS Leaders: Wonil + Linda + Jeff | Planning
Collect content documentation | Research | (Agile board) | Gather designs and specsGather content guidance (and/or content model)Gather developer notesGather research notes | Designer, content strategist,  developer, and researcher of pattern must be available to share documentation and relevant assets**contributor may need to write documentation** | Task assignee/Content creator | 1  (week one)
Fill in the content template | Creation | (Agile board)Box document | Take all documentation and assign to pattern content templateAdd new subsections as per pattern needs | See above | Task assignee/Content creator | 1 (week one)
Produce supporting assets | Creation | (Agile board)Sketch app/Photoshop | Do's and don'tsVisuals to support each sections and/or subsections of written guidelinesVideo/diagram/specs | Contributor to share [draft] assets and work with the Visual/UX Designer to ensure the assets are accurate. | Task assignee/Content creator | 1 (week two)–2 (week one)
Create draft design mockup | Creation | (Agile board)Sketch app | Create mockup of page with content and visualsShare mockup with all contributors for feedback | Availability of all contributors | Task assignee/Content creator or Visual/UX Designer | 2 (week one)
Share with the team to get feedback | Review |   |   |   |   | 2 (week one)
Update content or design | Creation | (Agile board)Sketch app |   | All contributors have reviewed | Task assignee/Content creator or Visual/UX Designer | 2 (week two)
Share with Carbon, IDL, ibm.com adopters | Review |   | Gather feedback from teams on content and page design |   | Task assignee/Content creator or Visual/UX Designer | 2 (week two)
Finalize documentation and update copy | Creation | (Agile board)Sketch app | Add any additional Carbon commentsEnsure language and style is consistent and updated Writer review and proof | Availability of Carbon | Task assignee/Content creator or Visual/UX Designer | 2 (week two)
(Optional) Review with IDL governance board | Review |   | Share/present pattern to IDL board for approval |   | Task assignee/Content creator or Visual/UX Designer | 2 (week two)
Finalize content and documentation | Creation | (Agile board)Sketch app | Add any additional Carbon Board commentsEnsure language and style is consistent and updated Writer review and proofReview with DDS leaders for approval |   | Task assignee/Content creator or Visual/UX DesignerApprover: Wonil + Linda + Jeff | 2 (week two)
Create a new page and publish on website | Publish | (Agile board)Github(markdowns and html code) | Publishing with markdown by Visual/UX DesignerPublishing with code by a Developer (as needed)PR preview link is readyPR review request set ( reviewer - Jenny or Wonil) | Final pattern documentation has been reviewed and approved by Wonil, Linda, Carbon– Pattern and guidelines have been approved by Carbon review board– All assets must be made available to publishers | Task assignee/Content creator or Visual/UX Designer | 2 (week two)
Website page go live | Release | (Agile board)Github | QA via the preview linkApprove the PR and merge the PR to master branch. | - Jenkin built | Jenny | 2 (week two)
Get adopter feedback | Review | (Ideation board) Cupcake website | Update roadmap / GitHubSlack communicationsShare outcome on Wake?Spot opportunity and make plan for improvementCatalog/consolidate feedback |   | Task assignee/Content creator or Visual/UX Designer | Iteration starts
