### ISSUE TITLE
Gather feedback on patterns organization prototypes

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/digital-design-ideation#74]
### User story
As a member of our team (DDS or Reboot) I need to understand how patterns are organized and what they are named so I can choose the right pattern for my design needs or contribute to the system.

### Objectives
We need to validate some of the ideas and proposals for reorganizing patterns.

### Tasks
- [x] Playback prototypes with DDS team
- [x] Playback prototypes with Reboot designers
- [x] Document feedback and inform direction

**Comment by larahanlon2** [comment]
Feedback from adopters Shixie, Pete, Lila and DDS team members:

Shixie, Pete, Lila, James, Olivia, Jenny

* “Love how you’re organizing (components = coded, patterns = guidelines)”
* Very clear.
* Patterns based on intent makes a lot of sense from a design and user perspective.
* Patterns as guidelines aligned to Carbon.
* Pete= I like calling out blocks as a group of components
* James = I don’t like blocks. It doesn’t mean anything. We will need to educate.
* Component types: simple Vs complex is a very clear way of differentiating between different levels of components
* Helpful to link patterns with other layouts, components, pages.

**Comment by larahanlon2** [comment]
On Monday July 13, Lara shared a recap of the leading proposal with the DDS team. The collated feedback, assumptions and questions, and proposed timeline can be found here: https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1594653276781?sender=larahanlon9022&key=f96804df-844e-4fc5-bbfb-7f0754ce519a

### Notes:

- It was agreed by the DDS leads and team members that the current proposal to **move all current layout patterns under components category is a positive path forward** and a good strategy. 
- It was agreed that we need to **align with Support and Cloud before** making a final decision to ensure there is alignment with these key adopter teams.
- It was agreed that the **current publishing priorities for the website should continue** (documentation of current layout patterns).
- Jeff opened an issue for **dev refactoring** and added the backlog for when the time comes to move patterns into components.
- **Coordination between website and storybook** will be important to make sure they are both the same i.e components = all coded UI, patterns are design intents and guidelines.
- We will need updated **definitions** for all terms and words.

**Comment by larahanlon2** [comment]
Presented at sprint. Closing.
