### ISSUE TITLE
Create publishing priority list for current inventory

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#75]
#### Objective

We currently have 43 total of components and layout patterns in the [Storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/overview-get-started--default). We need to have a clear view of which ones are meeting the publishing criteria (#55) so we can start the publishing process as soon as we can to bring the content to adopters through the website.

#### Task

- [x] Have the publishing criteria set up in a list format in [Mural](https://app.mural.co/invitation/mural/ibm14/1592586700298?sender=chsanche&key=0f7c3917-398c-4fc0-a429-ebe8667b20ad)
- [x] Add the 43 components and layout patterns to the [Mural](https://app.mural.co/invitation/mural/ibm14/1592586700298?sender=chsanche&key=0f7c3917-398c-4fc0-a429-ebe8667b20ad)
- [x] Work with Lara and Olivia to audit the 43 components and layout patterns
- [x] Share the priorities shared with the DDS team members

#### Acceptance criteria

- [x] Have the priorities list ready to assign to team members for content crafting (we will create individual task issues for the content crafting).

**Comment by JennySanchez** [comment]
**Task status as 06/25**

![Screen Shot 2020-06-25 at 1 40 31 PM](https://user-images.githubusercontent.com/45213839/85785463-f0676100-b6ee-11ea-812d-b88f3cfa5f14.png)

**Comment by JennySanchez** [comment]
We will use the Mural above for content crafting assignments.
