### ISSUE TITLE
IBM.com style model updates

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#76]
#### Objective
This epic is to conduct a series of activities in order to update the existing style models framework with the following focus areas

- Review existing style models
- Audit more IBM pages
- Audit more competitor pages
- Update the design intent list

#### Box folder
https://ibm.box.com/s/fz1psf2uc9iifl86xv5o72zwm4lqhyl4

#### Potential Tasks
- [x] Review IBM.com style model work from Wonil [dot-com--style-models--master--5.4.1](https://ibm.box.com/s/uhnwjo0xhvspj1uykqcuk661i2qnk8q2) 
- [x] Review the [stakeholder map](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1588088675654?sender=oliviaflory3358&key=abbe1158-661a-432f-aeeb-336eab4226ec) 
- [x] Audit IBM pages 
- [ ] Audit competitors
- [ ] Inventory design intents from audit #80 
- [ ] Update style models

**Comment by oscardumlao-ibm** [comment]
This was pre-Patterns work, and the initial audit was completed (https://airtable.com/tblL9jC7WnaKux99O/viwdshCsGz1uHyIZs?blocks=bip2kUC5xkV7zXr8D) and some findings were synthesized (https://ibm.ent.box.com/file/691175364280)
