### ISSUE TITLE
IBM.com style model work - stakholder interviews planning and set up

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#77]
#### Objective
(Coming soon - Wonil)

#### Tasks
- [x] Develop a list to interview
- [x] Conduct interviews
- [x] Synthesize interview findings and spot 3-4 areas of scaling, expansion, growth of the style model

#### Acceptance criteria:
- [x] Provide a synthesized list for scaling, expansion, growth of the style model

**Comment by oscardumlao-ibm** [comment]
Initial changes to Style Model intents were presented slightly before outset of Patterns. Here were the initial suggestions: https://ibm.ent.box.com/file/691176600846
