### ISSUE TITLE
Exp theme ideal state: Ideation

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#8]
### Objectives (tentative)
**The ultimate objective** is to understand the true scope of this work to inform involved parties (DDS + Carbon + leadership) so that the right strategy can be formulated.

- Define the areas that will be impacted by the expressive theme, such as documentation, code, etc
   - Define and understand each area
   - Estimate the LoE and scope for each area
- Set up tools, working methods, and processes
   - Stakeholder map (all level including collaborators and peer reviewers such as Carbon)
   - Tools and methods
   - Processes
   - Roadmap
- Identify next steps

### Tasks (tentative)
- [x] Set up a meeting to kick-off
- [x] Agree on the objectives and outcomes
- [ ] Discuss ideas on how to tackle this work
- [x] Create a stakeholder map
- [ ] Defining the landscape of the ideal state
- [ ] Set up tools, methods, and process
- [ ] Create next step stories

**Comment by wonilsuhibm** [comment]
What to do
- Rough impact map for Akira's RFC by the end of the sprint 8
- Will work on stakeholder map after the impact map
- 

# What is the ideal state?

### top level
- Having an expressive theme in which all components are scaled up as a whole for an optimal and coherent rendering of IBMm.com pages

### second level in support of the top level
- A single system supporting both productive and expressive
- It's easy for adopters to understand the system and use the two type sizes appropriately without getting confused

### third level in support of second level
- The landscape of this ideal state: identify areas such as documentation, code base, comms, training, design kit, etc
- Discuss 

### Etc
Let's look at how other companies are doing

**Comment by oliviaflory** [comment]
Shared expressive token audit Sketch file with Carbon on Friday, May 22nd. Akira had shared the PR with Carbon a week previously.

The Carbon team has a tight deadline for Phil this week, so they might not have time to review yet.

**Comment by oliviaflory** [comment]
Update: after reviewing Akira's PR the Carbon team has determined they do not have the bandwidth to support the expressive tokens and components. 

We will be moving forward with a proxy approach, and closing this issue
