### ISSUE TITLE
IBM.com style model: audit more IBM pages

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#80]
### Objective

We have the following design intents (hypothesis)
- Landing page
   - Eg) [home page](https://www.ibm.com/us-en/?ar=1)
   - Eg) [Topic landing page, Services](https://www.ibm.com/services?lnk=hpmse_ts&lnk2=learn)
- Navigational
   - Eg) [Products](https://www.ibm.com/products?lnk=hpmpr&lnk2=learn)
- Reading
   - Eg) [IBM.org](https://www.ibm.com/blogs/corporate-social-responsibility/2020/05/ibm-services-corps-empowers-jump-maths-transformation/)
- Informational
   - Eg) [SPSS pricing](https://www.ibm.com/products/spss-statistics/pricing), [SPSS features](https://www.ibm.com/products/spss-statistics/details)
- Dashboard
   - Eg) [IBM Cloud](https://cloud.ibm.com/)
   - Eg) [My IBM](https://myibm.ibm.com/dashboard/)
- Transactional
   - Eg) Checkout process, login process

The main objective of this story is to make sure that the above list is comprehensive and reflects our needs by collecting page examples and mapping them to the design intents.

### Task
- [x] Find page examples of the above design intents from within IBM and collect them per design intent. Add more intents if identified.

### Stretch tasks
- [ ] Find page examples of the above design intents from competitors and collect them per design intent
- [ ] [Map page types](https://ibm.box.com/s/61bi2xrwmjdulcsj1scjomwr2n0s0mgf) to design intents (hypothesis)

##### Internal digital properties, priorities
[IBM Cloud](http://www.ibm.com/cloud)
[IBM Developer](https://developer.ibm.com/)
[IBM Research](http://research.ibm.com/)
[Redhat](https://www.redhat.com/en)

##### Internal digital properties, stretch
IBM Security
IBM.org
IBM Skills

##### Competitors, priorities
Google Cloud
AWS

##### Competitors, stretch
SAP
Oracle
Accenture
GE
Publicis Sapient
SalesForce

### Acceptance criteria
- [x] Updated list of design intents
- [x] Page examples collected per intents
- [x] (Maybe) have some (opinionated) POV on which pages work better.

**Comment by oscardumlao-ibm** [comment]
Update: 30 pages logged across Cloud, Developer, and smaller IBM.com subgroups. New Intent proposed, "Blogs", for blog homepages that link to editorial content.

**Comment by oscardumlao-ibm** [comment]
Update: 90 pages logged through to some of the stretch IBM.com properties. "Blogs" renamed to "Listing" for more general application, and matching Wonil's Sketch file. A summary deck is in progress.

**Comment by oscardumlao-ibm** [comment]
Airtable: https://airtable.com/tblL9jC7WnaKux99O/viwyZ9JdHuhx1lBcW?blocks=bip2kUC5xkV7zXr8D
Deck: https://ibm.box.com/s/glhzsijane0avppcbb4wb3y9zz94ukey
