### ISSUE TITLE
Identify potential subcategories for components

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/digital-design-ideation#84]
### Objective
If we are moving current patterns into components based on the latest prototypes we need to consider the different types of components that will be in the library. Subcategories may help adopters to understand and find the type of component they need.

### Tasks
- [ ] Explore different ways of sub categorizing components and patterns
- [ ] Test labels with DDS and Reboot team members
- [ ] Gather feedback
- [ ] Create and explore definitions to match the sub categories

**Comment by larahanlon2** [comment]
See [Mural](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1592925542873?sender=larahanlon9022&key=3e99fc46-6800-44a7-bfcf-b4a5e9e75e85) for potential sub-categories. Feedback so far: 

**Simple + Complex** is favored by many team members due to the simplicity of language. However, this many not be explicit enough for new adopters to understand. Does this reflect the mindset of a designer or dev?

**Comment by larahanlon2** [comment]
WIP definitions for commonly used words/labels added to the Mural board. We will need to decide what works best for internal and external communication. Wonil suggested a card sorting exercise for category labels. We could do something similar for definitions, perhaps.

https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1592925542873?sender=larahanlon9022&key=3e99fc46-6800-44a7-bfcf-b4a5e9e75e85

**Comment by larahanlon2** [comment]
Latest decision from Wonil, Lara, Jenny, Jacob:

We're going to use the labels **UI components** and **Layout components** to sub-categorize components on the website. We will not be impacting the IA/nav on the website or Storybook for now. We will use these labels on the overview page only as a first step, and gather feedback from adopters to see if these sub-categories make sense.

1. **UI components** will include button group, card, link list, masthead, footer, link with icon.
2. **Layout components** will include all previous layout patterns such as content group — pictograms, card section, lead space.
