### ISSUE TITLE
Ideation: Website task work process, tooling improvement, and content update cadence/schedule

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#86]
> As an IBM.com Library website content creator,

> I need a way to work efficiently, 

> so that I can work on the website content with confidence and push myself for improvement at all times.

### Task

- [ ] Get feedback from the team members around what I need to make improvements on when it comes to processing and tooling for website publishing.
- [ ] Research how others internally and externally work around the challenge.
- [ ] Try the possible solutions.

### Acceptance criteria
- [ ] Make improvements through time and share findings with the DDS team members and leadership team.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Please feel free to create any subtasks (and linked to this EPIC) you would like us to work on or try around process and tooling improvement.

**Comment by JennySanchez** [comment]
This Epic is no longer relevant to our work or priority and will be closed.
FYI: @RobertaJHahn
